spring.application.name=ai_engineering

server.port=${SERVER_PORT:8080}

spring.config.import=optional:file:.env[.properties]

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

spring.ai.openai.api-key=${OPEN_API_KEY}
spring.ai.openai.base-url=${OPEN_API_BASE_URL}
spring.ai.openai.chat.model=${CHAT_MODEL}
eureka.client.service-url.defaultZone = ${SERVER_URL}

spring.ai.chat.memory.repository.jdbc.initialize-schema=${CHAT_MEMORY_INIT_SCHEMA:always}